using System;
using System.Linq;

namespace CSharpAlgorithms.LeetCode
{
    /*
        LeetCode 389. Find The Difference
        https://leetcode.com/contest/2/problems/find-the-difference/

        Given two strings s and t which consist of only lowercase letters.
        String t is generated by random shuffling string s and then add one more letter at a random position.
        Find the letter that was added in t.
    */

    public class FindTheDifference
    {
        public static void Run()
        {
            string s = "abcd";
            string t = "abcde";

            Console.WriteLine(FindTheDifferenceOfStrings(s, t));
        }

        private static char FindTheDifferenceOfStrings(string s, string t)
        {
            char[] setA = s.ToCharArray();
            char[] setB = t.ToCharArray();

            char diff = ' ';

            foreach (var c in setB)
            {
                if (!setA.Contains(c))
                {
                    diff = c;
                }
            }
            return diff;
        }
    }
}